name: Deployment Workflow

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3 
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: deploy_dist
          path: build

  deploy:
    name: Deploy
    if: ${{ github.event_name == 'push' && github.ref == 'main' }} 
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      - name: Download Build
        uses: actions/download-artifact@v3 
        with:
          name: deploy_dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist
